name: Taser
version: 1.0
main: com.mike.taser.Main
api-version: "1.17"
softdepend: [QualityArmory]

author: Mike
website: https://t.me/mike_workshop
description: Plugin Taser con ricariche, cooldown, logs ed eventi personalizzati.

commands:
  taser:
    description: Comando principale del plugin Taser
    permission-message: §cNon hai il permesso necessario per usare questo comando.
